// Generated by generate_entries.py. Edit content/timeline/*.json instead.
window.TIMELINE_ENTRIES = [
  {
    "date": "2026-09-14",
    "title": "An afternoon close to home [PLACEHOLDER]",
    "place": "Carmel, Indiana",
    "coords": null,
    "people": [],
    "tags": [
      "personal"
    ],
    "photo_original": "/assets/portrait-nick.jpg",
    "photo_styled": null,
    "blurb": "[PLACEHOLDER] A quiet afternoon around Carmel. This is fictional sample copy; the portrait is an existing site asset, not a photo of this outing.",
    "visibility": "public",
    "date_end": null,
    "date_precision": "day",
    "subtitle": null,
    "chapter": null,
    "kind": "moment",
    "links": [],
    "metrics": []
  },
  {
    "date": "2026-09-12",
    "title": "Time with Diane and Bailey [PLACEHOLDER]",
    "place": "Carmel, Indiana",
    "coords": null,
    "people": [
      "Diane",
      "Bailey"
    ],
    "tags": [
      "personal"
    ],
    "photo_original": null,
    "photo_styled": null,
    "blurb": "[PLACEHOLDER] A little time together, with nowhere urgent to be. Fictional family check-in for this preview.",
    "visibility": "public",
    "date_end": null,
    "date_precision": "day",
    "subtitle": null,
    "chapter": null,
    "kind": "moment",
    "links": [],
    "metrics": []
  },
  {
    "date": "2026-09-10",
    "title": "The work behind a gathering",
    "place": "Indiana",
    "coords": null,
    "people": [],
    "tags": [
      "personal",
      "professional"
    ],
    "photo_original": null,
    "photo_styled": null,
    "blurb": "The Wilds and Laural Mill are part of my operating context. This sample entry brings venue work into the timeline alongside life and product work.",
    "visibility": "public",
    "date_end": null,
    "date_precision": "day",
    "subtitle": null,
    "chapter": null,
    "kind": "moment",
    "links": [],
    "metrics": []
  },
  {
    "date": "2025-01-01",
    "title": "Building Ballpark",
    "place": null,
    "coords": null,
    "people": [],
    "tags": [
      "professional"
    ],
    "photo_original": "/assets/ballpark-estimate.png",
    "photo_styled": null,
    "blurb": "Ballpark is AI estimating at ballpark.build. The product grew out of the estimating work inside a construction business.",
    "visibility": "public",
    "date_end": null,
    "date_precision": "day",
    "subtitle": null,
    "chapter": null,
    "kind": "moment",
    "links": [],
    "metrics": []
  },
  {
    "date": "2024-10-01",
    "title": "Building Off Leash Construction",
    "place": "Indianapolis, Indiana",
    "coords": null,
    "people": [],
    "tags": [
      "professional"
    ],
    "photo_original": null,
    "photo_styled": null,
    "blurb": "Off Leash Construction reached $3M+ in year one, with a maintenance department covering 3,000+ doors.",
    "visibility": "public",
    "date_end": null,
    "date_precision": "day",
    "subtitle": null,
    "chapter": null,
    "kind": "moment",
    "links": [],
    "metrics": []
  },
  {
    "date": "2023-04-18",
    "title": "Bailey arrives",
    "place": "Carmel",
    "coords": null,
    "people": [
      "Bailey",
      "Diane"
    ],
    "tags": [
      "personal"
    ],
    "kind": "milestone",
    "chapter": "Family",
    "photo_original": null,
    "photo_styled": null,
    "blurb": "Our family grew by one. A warm, quiet milestone.",
    "visibility": "public",
    "date_end": null,
    "date_precision": "day",
    "subtitle": null,
    "links": [],
    "metrics": []
  },
  {
    "date": "2022-03-01",
    "title": "Meta Reality Labs",
    "place": null,
    "coords": null,
    "people": [],
    "tags": [
      "professional"
    ],
    "photo_original": null,
    "photo_styled": null,
    "blurb": "Portal units grew 300% and Oculus units grew 450% during my tenure.",
    "visibility": "public",
    "date_end": null,
    "date_precision": "day",
    "subtitle": null,
    "chapter": null,
    "kind": "moment",
    "links": [],
    "metrics": []
  },
  {
    "date": "2019-11-01",
    "title": "Growing peripherals at Corsair",
    "place": null,
    "coords": null,
    "people": [],
    "tags": [
      "professional"
    ],
    "photo_original": null,
    "photo_styled": null,
    "blurb": "#1 NPD share and more than 50% year-over-year growth. Rookie of the Year in 2018, followed by the President's Award in 2019.",
    "visibility": "public",
    "date_end": null,
    "date_precision": "day",
    "subtitle": null,
    "chapter": null,
    "kind": "moment",
    "links": [],
    "metrics": []
  },
  {
    "date": "2017-10-01",
    "title": "Razer, with Amazon in focus",
    "place": null,
    "coords": null,
    "people": [],
    "tags": [
      "professional"
    ],
    "photo_original": null,
    "photo_styled": null,
    "blurb": "A $150M budget and a team of six. 70% year-over-year growth and Amazon Gold.",
    "visibility": "public",
    "date_end": null,
    "date_precision": "day",
    "subtitle": null,
    "chapter": null,
    "kind": "moment",
    "links": [],
    "metrics": []
  },
  {
    "date": "2016-10-01",
    "title": "Wedding",
    "place": null,
    "coords": null,
    "people": [
      "Diane"
    ],
    "tags": [
      "personal"
    ],
    "kind": "milestone",
    "chapter": "Family",
    "photo_original": null,
    "photo_styled": null,
    "blurb": "A day that started a life together. Short notes only for now.",
    "visibility": "public",
    "date_end": null,
    "date_precision": "day",
    "subtitle": null,
    "links": [],
    "metrics": []
  }
];
