"""Bundle public timeline JSON for HTTP and file:// previews. Run from any directory."""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent

# Optional schema (defaults when omitted from source JSON):
#   date_end        ISO date or null — if set, render as a period/range
#   date_precision  day|month|year (default day)
#   subtitle        string or null
#   chapter         string era label or null
#   kind            moment|period|milestone (default moment)
#   links           [{label, url}]
#   metrics         [{label, value}] — claim-locked values only
# Core (unchanged): date, title, place, coords, people, tags,
#   photo_original, photo_styled, blurb, visibility
ALLOWED_PRECISION = {'day', 'month', 'year'}
ALLOWED_KIND = {'moment', 'period', 'milestone'}


def normalize(entry, source):
    """Pass through core fields; apply optional schema defaults."""
    out = dict(entry)
    if 'date_end' not in out:
        out['date_end'] = None
    precision = out.get('date_precision') or 'day'
    if precision not in ALLOWED_PRECISION:
        raise SystemExit(f'{source.name}: date_precision must be day|month|year')
    out['date_precision'] = precision
    if 'subtitle' not in out:
        out['subtitle'] = None
    if 'chapter' not in out:
        out['chapter'] = None
    kind = out.get('kind') or 'moment'
    if kind not in ALLOWED_KIND:
        raise SystemExit(f'{source.name}: kind must be moment|period|milestone')
    out['kind'] = kind
    links = out.get('links')
    out['links'] = links if isinstance(links, list) else []
    metrics = out.get('metrics')
    out['metrics'] = metrics if isinstance(metrics, list) else []
    if out['date_end'] is not None and not isinstance(out['date_end'], str):
        raise SystemExit(f'{source.name}: date_end must be ISO date string or null')
    return out


entries = []
for source in sorted((HERE.parent / 'content/timeline').glob('*.json')):
    entry = json.loads(source.read_text())
    if entry['visibility'] == 'public':
        entries.append(normalize(entry, source))
entries.sort(key=lambda entry: entry['date'], reverse=True)
(HERE / 'entries.js').write_text(
    '// Generated by generate_entries.py. Edit content/timeline/*.json instead.\n'
    + 'window.TIMELINE_ENTRIES = ' + json.dumps(entries, indent=2, ensure_ascii=True) + ';\n'
)
print(f'Bundled {len(entries)} public entries.')
