"""Bundle public timeline JSON for HTTP and file:// previews. Run from any directory."""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
entries = []
for source in sorted((HERE.parent / 'content/timeline').glob('*.json')):
    entry = json.loads(source.read_text())
    if entry['visibility'] == 'public':
        entries.append(entry)
entries.sort(key=lambda entry: entry['date'], reverse=True)
(HERE / 'entries.js').write_text(
    '// Generated by generate_entries.py. Edit content/timeline/*.json instead.\n'
    + 'window.TIMELINE_ENTRIES = ' + json.dumps(entries, indent=2, ensure_ascii=True) + ';\n'
)
print(f'Bundled {len(entries)} public entries.')
